# Usign the Clean Blog theme

title: Mathematical Tours of Data Sciences
author: mathematical-tours
email: gabriel.peyre@ens.fr
description: Mathematical Tour of Data Sciences
baseurl: ""
url: "http://mathematical-tours.github.io/"
github_username:  mathematical-tours

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: Mathematical Tours of Data Sciences
gems:
  - jekyll-feed
  - jekyll-paginate
