# Usign the Clean Blog theme

title: Artigos e Amigos
author: mariaaseret
email: mariat95@gmail.com
description: Artigos e Amigos
baseurl: ""
url: "https://artigos-e-amigos.github.io/"
github_username:  artigos-e-amigos

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: Artigos e Amigos
gems:
  - jekyll-feed
  - jekyll-paginate
